defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

url: "https://help.keboola.com"

exclude:
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

sass:
  style: compressed

gems:
  - jekyll-sitemap
