jekyll:
  image: quay.io/keboola/docs-jekyll
  tty: true
  stdin_open: true
  volumes:
    - ./:/code:cached
  working_dir: /code
  ports:
    - "5000:4000"
  command: jekyll serve --watch -H 0.0.0.0 --force_polling

aws:
  image: quay.io/keboola/aws-cli
  volumes:
    - ./:/code
  working_dir: /code
